######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 20 18:11:46 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../Status.h ../../Enum.h
SOURCES += testEnum.cpp ../../Status.cpp
