######################################################################
# Automatically generated by qmake (2.01a) mar. mars 18 19:24:01 2008
######################################################################

TEMPLATE = app
TARGET = testPackage
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -L../../ -lqpackagekit
QT += dbus

# Input
HEADERS += ../../Package.h
SOURCES += testPackage.cpp 
