######################################################################
# Automatically generated by qmake (2.01a) mar. oct. 9 23:16:51 2007
######################################################################

TEMPLATE = subdirs
SUBDIRS = lib gui pk-update-icon-qt

