######################################################################
# Automatically generated by qmake (2.01a) mar. mars 18 19:24:01 2008
######################################################################

TEMPLATE = app
TARGET = backendDetails
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -L../../ -lpackagekit-qt
QT += dbus

# Input
HEADERS += ../../QPackageKit.h
SOURCES += backendDetails.cpp
