######################################################################
# Automatically generated by qmake (2.01a) jeu. oct. 11 23:31:54 2007
######################################################################

TEMPLATE = app
TARGET = qpackagekit
DEPENDPATH += .
INCLUDEPATH += .

LIBS += ../lib/libqpackagekit.so.0.0.1

# Input
HEADERS += MainWindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp MainWindow.cpp
