######################################################################
# Automatically generated by qmake (2.01a) mar. mars 18 19:24:01 2008
######################################################################

TEMPLATE = app
TARGET = testSearch
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -L../../ -lpackagekit-qt
QT += dbus

# Input
HEADERS += testCallback.h
SOURCES += testSearch.cpp testCallback.cpp
