######################################################################
# Automatically generated by qmake (2.01a) mer. oct. 17 18:12:02 2007
######################################################################

TEMPLATE = lib
VERSION = 0.0.1
TARGET = qpackagekit
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qdbus

# Input
HEADERS += QPackageKitInterface.h QPackageKitClient.h 
SOURCES += QPackageKitInterface.cpp QPackageKitClient.cpp enums.cpp
