######################################################################
# Automatically generated by qmake (2.01a) mar. mars 18 19:24:01 2008
######################################################################

TEMPLATE = app
TARGET = testFinished
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -L../../ -lqpackagekit
QT += dbus

# Input
HEADERS += Receiver.h
SOURCES += testFinished.cpp Receiver.cpp
