######################################################################
# Automatically generated by qmake (2.01a) mer. avr. 30 00:08:43 2008
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FilterMenu.h
SOURCES += FilterMenu.cpp main.cpp
