######################################################################
# Automatically generated by qmake (2.01a) ven. mars 28 19:24:26 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += dbus

# Input
HEADERS += ../../Client.h ../../DBusProxy.h ../../Status.h ../../Enum.h
SOURCES += testStatus.cpp ../../Client.cpp ../../DBusProxy.cpp ../../Status.cpp
